### ISSUE TITLE
What is wrong with Blender 2.78?!?

### ISSUE THREAD

**Issue by pelednoam** [pelednoam/mmvt#9]
The rendering takes forever!!!
Maybe the default rendering properties are different?

**Comment by pelednoam** [comment]
Closing old issues? ☺️

**Comment by ohadfel** [comment]
Yep

On Oct 15, 2017 15:02, "Noam Peled" <notifications@github.com> wrote:

Closing old issues? ☺️

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/pelednoam/mmvt/issues/9#issuecomment-336706975>, or mute
the thread
